server:
  port: 1308
spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:1390/friends_db
    user: friends_user
    password: friends_password
  datasource:
    url: jdbc:postgresql://localhost:1390/friends_db
    username: friends_user
    password: friends_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rmq-user}
    password: ${RABBITMQ_PASSWORD:rmq-pass}
  cloud.stream.bindings:
    userDataSyncEvent-in-0:
      destination: ${app.id}_USER_DATA_SYNC_EVENT
    notificationEvent-out-0:
      destination: ${app.id}_NOTIFICATION_EVENT

app:
  jwt-token:
    permit-all:
      - /api/users/registration
      - /api/users/login
    root-path: /api
    secret: qwerqwerqwerqwetruiqywterqiuwyertqiwueyrtqwiueyrtqwuieyrtqwiueyrtqwuerqqqwyeurtqiwuyertqiuwyetrqiuwyetrqiuwyetrqwuiyertqwuyiertqwuiyertqwuiyertqwuieytrquwyetruqiwyetruiqwyretiuqywetuqwyetuqwyretqiuwyretqiwueyrtqiuwerytqiwueyrtqiuweyrtqwuieyrtqwueiyrtqweuir
    expiration: 1800000
  integrations:
    root-path: /integration
    api-key: ac546098c1c44ac2b2ae132f89c82e7e345d25a1h46474e75a78f9a5ce496060c


logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG

