server:
  port: 8007
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ithirteeng
    password: ithirteeng
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

