server:
  port: 1301
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_service_db
    username: ithirteeng
    password: ithirteeng
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  jwt-token:
    permit-all:
      - /api/users/registration
      - /api/users/login
    root-path: /api
    secret: qwerqwerqwerqwetruiqywterqiuwyertqiwueyrtqwiueyrtqwuieyrtqwiueyrtqwuerqqqwyeurtqiwuyertqiuwyetrqiuwyetrqiuwyetrqwuiyertqwuyiertqwuiyertqwuiyertqwuieytrquwyetruqiwyetruiqwyretiuqywetuqwyetuqwyretqiuwyretqiwueyrtqiuwerytqiwueyrtqiuweyrtqwuieyrtqwueiyrtqweuir
    expiration: 50000
  integrations:
    root-path: /integration
    api-key: ac546098c1c44ac2b2ae132f89c82e7e345d25a1h46474e75a78f9a5ce496060c–Ø