server:
  port: 1311

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:1394/files_db
    user: files_user
    password: files_password
  datasource:
    url: jdbc:postgresql://localhost:1394/files_db
    username: files_user
    password: files_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

minio:
  access-key: foGQ56VUDXn63a0JpNFj
  secret-key: KxDdv6vBG5IGXNr5jzuItMljfDp15n1YsFLgHCrU
  bucket: messenger-bucket
  url: http://localhost:1401

app:
  jwt-token:
    permit-all:
      - /api/users/registration
      - /api/users/login
    root-path: /api
    secret: qwerqwerqwerqwetruiqywterqiuwyertqiwueyrtqwiueyrtqwuieyrtqwiueyrtqwuerqqqwyeurtqiwuyertqiuwyetrqiuwyetrqiuwyetrqwuiyertqwuyiertqwuiyertqwuiyertqwuieytrquwyetruqiwyetruiqwyretiuqywetuqwyetuqwyretqiuwyretqiwueyrtqiuwerytqiwueyrtqiuweyrtqwuieyrtqwueiyrtqweuir
    expiration: 1800000
  integrations:
    root-path: /integration
    api-key: ac546098c1c44ac2b2ae132f89c82e7e345d25a1h46474e75a78f9a5ce496060c


logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG

